---
# Obtención Valor UF

Se pide confeccionar un programa en python para la obtención de la uf del mes de Octubre de 2021 y posteriormente **almacenarla en una planilla excel** tal como el siguiente ejemplo.


| Dia | Valor |
|---|---|
| 1 | 29936.45 |
| 2 | 29947.64 |
| 3 | 29956.23 |
| 4 | 30016.98 |
| ... | ... |


La siguiente url contiene datos del valor de la UF.

    http://www.sii.cl/valores_y_fechas/uf/uf2021.htm

In [147]:
import pandas as pd

import requests
from bs4 import BeautifulSoup

In [220]:
url = 'http://www.sii.cl/valores_y_fechas/uf/uf2021.htm'
r=requests.get(url)
tables = pd.read_html(url)
octubre=tables[2]

primero=octubre.iloc[:10,:2]
segundo=octubre.iloc[:10,2:4]
tercero=octubre.iloc[:11,4:6]


primeroo=primero.rename({'Octubre': 'Dia','Octubre.1': 'Valor'}, axis=1)
segundoo=segundo.rename({'Octubre.2': 'Dia','Octubre.3': 'Valor'}, axis=1)
terceroo=tercero.rename({'Octubre.4': 'Dia','Octubre.5': 'Valor'}, axis=1)

k=pd.merge(primeroo,segundoo,how="outer")
l=pd.merge(k,terceroo,how="outer")
l
final=l

     Dia      Valor
0    1.0  30.092,38
1    2.0  30.096,38
2    3.0  30.100,39
3    4.0  30.104,39
4    5.0  30.108,40
5    6.0  30.112,40
6    7.0  30.116,41
7    8.0  30.120,42
8    9.0  30.124,43
9   10.0  30.136,02
10  11.0  30.147,62
11  12.0  30.159,23
12  13.0  30.170,83
13  14.0  30.182,44
14  15.0  30.194,06
15  16.0  30.205,68
16  17.0  30.217,31
17  18.0  30.228,94
18  19.0  30.240,57
19  20.0  30.252,21
20  21.0  30.263,85
21  22.0  30.275,50
22  23.0  30.287,15
23  24.0  30.298,81
24  25.0  30.310,47
25  26.0  30.322,13
26  27.0  30.333,80
27  28.0  30.345,48
28  29.0  30.357,16
29  30.0  30.368,84
30  31.0  30.380,53

NameError: name 'di' is not defined